import { PerformanceMonitor, PerspectiveCamera } from "@react-three/drei";
import { Canvas } from "@react-three/fiber";
import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";
import { Scene } from "../components/3d/Scene";
import { useEffect, useRef, useState } from "react";
import NavBar from "~/components/navbar";
import {
  useSpring,
  config,
  a,
  useSpringRef,
  useChain,
} from "@react-spring/web";
export default function Home() {
  const [dpr, setDpr] = useState<number>(1);
  const [m, setM] = useState<number>(0.002);
  const pages = useRef<number>(8);
  const [perm, setPerm] = useState<boolean>(false)
  const [currentPage, setCurrentPage] = useState<number>(1)
  const [isMobile, setIsMobile] = useState<boolean>(false);

  // updates current page on scroll
  useEffect(() => {
    setCurrentPage(Math.floor(m / (1/pages.current)) + 1)
  }, [m])


  const springFrame = useSpring({
    opacity: currentPage == 1 ? 1 : 0,
    pointerEvents: currentPage == 1 ? "auto" : "none",
  });

  const springProductShowcase = useSpring({
    opacity: currentPage  == 2 ? 1 : 0,
    pointerEvents: currentPage == 2 ? "auto" : "none",
  });

  const scrollSpring = useSpring({
    from: {
      bottom: "-10rem"
    },
    to: {
      bottom: "1rem"
    },
    config: config.wobbly
  });

  // haqndles isMobile
  useEffect(() => {
    function handleResize() {
      let check = false;
      (function (a) {
        if (
          /(android|bb\d+|meego).+mobile|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(hone|od)|iris|kindle|lge |maemo|midp|mmp|mobile.+firefox|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|series(4|6)0|symbian|treo|up\.(browser|link)|vodafone|wap|windows ce|xda|xiino/i.test(
            a,
          ) ||
          /1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|yas\-|your|zeto|zte\-/i.test(
            a.substr(0, 4),
          )
        )
          check = true;
      })(navigator.userAgent || navigator.vendor);
      setIsMobile(check);
    }
    window.addEventListener("resize", handleResize);
    return () => window.removeEventListener("resize", handleResize);
  }, []);

  // handle wheel event on desktop

  useEffect(() => {
    if (isMobile) {
      window.addEventListener("scroll", (e) => {
        setM(
          Math.floor(
            (window.scrollY /
              (document.documentElement.scrollHeight - window.innerHeight)) *
              100,
          ),
        );
      });
    } else {
      window.addEventListener("wheel", (e) => {
        if (
          m + Math.sign(e.deltaY) / 100 > 0.002 &&
          m + Math.sign(e.deltaY) / 100 <= 1
        ) {
          setM(m + Math.sign(e.deltaY) / 100);
        }
      });
    }
  });

  // bg-colors
  const bgColor = {
    1: "bg-black",
    2: "bg-[#001a1e]",
    3: "bg-red-950",
  };


  return (
    <>
      <Head>
        <title>Martnetics</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="selection:text-blue-700">
        <div className="relative h-full w-full overflow-hidden">
          {/* Progress */}
          <div className="pointer-events-none absolute bottom-6 right-[1rem] z-50 text-xl font-black text-white lg:text-2xl 2xl:text-4xl">
            {Math.floor(m * 100)}%
          </div>

          {/* Landing page */}
          <a.div
            className="relative z-20 flex h-screen flex-col justify-between"
            style={springFrame as any}
          >
            <div className="flex flex-col justify-center text-white tracking-widest w-1/2">
              <div className="text-6xl font-black tracking-tight md:text-8xl 2xl:text-9xl">
                Add Another Dimension
              </div>
              <div className="text-xl font-black tracking-tight md:text-8xl">
                With Martnetics.
              </div>
            </div>

            <a.div className="text-xl font-black uppercase tracking-widest text-white pl-4 relative" style={scrollSpring}>
              <img src="/loader_2.png" className="w-12 inline animate-spin mb-1"/>
              <span className="pl-1">Scroll Down</span>
            </a.div>

          </a.div>

          {/* Watch Markup */}
          <div className="absolute left-0 top-0">
            <div className="flex h-screen flex-col justify-center px-8 text-blue-300">
              <a.div className="z-20" style={springProductShowcase as any}>
                <div className="text-4xl font-black">Selling A Product</div>
                <div className="text-xl font-light">
                  Allow us to showcase it 🌟
                </div>
              </a.div> 
              <a.div className="z-20 text-base font-light text-white/50 tracking-wide" style={springProductShowcase as any}>?: drag the watch around</a.div>
            </div>
          </div>

          {/* R3F Canvas */}
          <div className="fixed left-0 top-0 h-screen w-full">
            <Canvas
              shadows
              gl={{ powerPreference: "high-performance" }}
              dpr={dpr}
              className={
                "transition-colors duration-700 " +
                bgColor[(Math.floor(m / (1/pages.current)) + 1) as keyof typeof bgColor]
              }
            >
              <PerformanceMonitor
                onIncline={() => setDpr(2)}
                onDecline={() => setDpr(1)}
              />
              <Scene m={m} currentPage={currentPage} isMobile={isMobile} handleState={setPerm} />
            </Canvas>
          </div>
        </div>
      </main>
    </>
  );
}
