import { PerformanceMonitor, PerspectiveCamera } from "@react-three/drei";
import { Canvas } from "@react-three/fiber";
import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";
import { Scene } from "../components/3d/Scene";
import { useEffect, useRef, useState } from "react";

export default function Home() {
  const [dpr, setDpr] = useState<number>(1);
  
  return (
    <>
      <Head>
        <title>Martnetics</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="selection:bg-primary selection:text-black">
        <div className="h-full w-full overflow-hidden">
          <div className="fixed left-0 top-0 h-screen w-full">
            <Canvas
              shadows
              gl={{ powerPreference: "high-performance" }}
              dpr={dpr}
            >
              <PerformanceMonitor
                onIncline={() => setDpr(2)}
                onDecline={() => setDpr(1)}
              ></PerformanceMonitor>
              <Scene />
            </Canvas>
          </div>
        </div>
      </main>
    </>
  );
}
